esphome:
  name: dmx

esp8266:
  board: d1_mini_pro
  restore_from_flash: true

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: "xxx"
  password: "xxx"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
#   ap:
#     ssid: "Dmx Fallback Hotspot"
#     password: "GPaqLo2JYO9H"

# captive_portal:

external_components:
  - source: github://andyboeh/esphome-dmx512

uart:
  id: uart_bus
  baud_rate: 250000
  tx_pin:
    number: GPIO2 #ESP8266
    allow_other_uses: true # for ESPHome >= 2023.12.0
  stop_bits: 2

dmx512:
  id: dmx
  uart_id: uart_bus
  tx_pin:
    number: GPIO2 #ESP8266
    allow_other_uses: true # for ESPHome >= 2023.12.0
  uart_num: 1
  force_full_frames: true

output:
  - platform: dmx512
    channel: 1
    universe: dmx
    id: dmx_1

  - platform: dmx512
    channel: 2
    universe: dmx
    id: dmx_2

  - platform: dmx512
    channel: 3
    universe: dmx
    id: dmx_3

  - platform: dmx512
    channel: 4
    universe: dmx
    id: dmx_4

  - platform: dmx512
    channel: 5
    universe: dmx
    id: dmx_5

  - platform: dmx512
    channel: 6
    universe: dmx
    id: dmx_6

  - platform: dmx512
    channel: 7
    universe: dmx
    id: dmx_7

  - platform: dmx512
    channel: 8
    universe: dmx
    id: dmx_8

  - platform: dmx512
    channel: 9
    universe: dmx
    id: dmx_9

  - platform: dmx512
    channel: 10
    universe: dmx
    id: dmx_10

light:
  - platform: monochromatic
    name: "Mode Selection"
    output: dmx_1
    id: light_dmx_1
    default_transition_length: 0s
    gamma_correct: 0

  - platform: monochromatic
    name: "Pattern/Mode"
    output: dmx_2
    id: light_dmx_2
    default_transition_length: 0s
    gamma_correct: 0

  - platform: monochromatic
    name: "Rotation"
    output: dmx_3
    id: light_dmx_3
    default_transition_length: 0s
    gamma_correct: 0

  - platform: monochromatic
    name: "Horizontal Rotation (width)"
    output: dmx_4
    id: light_dmx_4
    default_transition_length: 0s
    gamma_correct: 0

  - platform: monochromatic
    name: "Vertical Rotation (height)"
    output: dmx_5
    id: light_dmx_5
    default_transition_length: 0s
    gamma_correct: 0

  - platform: monochromatic
    name: "Horizontal Position"
    output: dmx_6
    id: light_dmx_6
    default_transition_length: 0s
    gamma_correct: 0

  - platform: monochromatic
    name: "Vertical Position"
    output: dmx_7
    id: light_dmx_7
    default_transition_length: 0s
    gamma_correct: 0

  - platform: monochromatic
    name: "Pattern Size"
    output: dmx_8
    id: light_dmx_8
    default_transition_length: 0s
    gamma_correct: 0

  - platform: monochromatic
    name: "Color"
    output: dmx_9
    id: light_dmx_9
    default_transition_length: 0s
    gamma_correct: 0

  - platform: monochromatic
    name: "Lines/Dots"
    output: dmx_10
    id: light_dmx_10
    default_transition_length: 0s
    gamma_correct: 0
